### ISSUE TITLE
Registry bootstrap doesn't need to look at tags

### ISSUE THREAD

**Issue by Jamstah** [oci-playground/distribution-spec#12]
On upgrading, this line:
> When registries add support for the Referrers API, this API needs to account for manifests that were pushed before the API was available using the [Client Implementation's tag schema](client-implementation.md#referrers-api).

Could we just remove this part?
> using the [Client Implementation's tag schema](client-implementation.md#referrers-api)

The registry doesn't need to look at the tags, it would make more sense for it to look at all the manifests and just ignore the tags.

**Comment by sudo-bmitch** [comment]
Cleaning this up since we're archiving things from the working group. We've pushed these changes upstream. A registry can look at every manifest, but there's push back for registries with a lot of historical data. They don't want to reparse every manifest ever uploaded. Allowing that to be scoped to only the manifests listed in the index manifests found by the tag schema lets them skip almost all manifests in their scan, significantly reducing the overhead of implementing the feature for the early adopters.

If this is still a concern, please raise it in the upstream project since the changes have been merged there.
